### ISSUE TITLE
Compatibility with Neos 5

### ISSUE THREAD

**Issue by simonschaufi** [networkteam/Networkteam.Neos.FrontendLogin#13]
Thank you for this great package. Unfortunately it is not compatible with Neos 5. Are you planning an update soon? Otherwise I need to use `Flowpack.Neos.FrontendLogin`

**Comment by ger4003** [comment]
Hi @simonschaufi,

Haven't tried the package with Neos 5 yet. Can you describe the error or provide a PR?

**Comment by simonschaufi** [comment]
@ger4003 I'm not aware of any error, it's basically that the composer dependencies are just for Neos 4 right now
